name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: shashankv1999/hello-python:${{ steps.commit.outputs.short }}
      
      - name: replace in values.yaml
        run: |
          pwd
          cd /home/runner/work/github-hello-action/github-hello-action
          ls python-hello/
          sed -i 's/tag'":"' .*/tag'":"' '"${{ steps.commit.outputs.short }}"'/g' ./python-hello/values.yaml
          cat ./python-hello/values.yaml
